# Generated by Django 3.2.5 on 2021-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('address', models.CharField(max_length=10000)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('email', models.CharField(default='abc@abc.com', max_length=500)),
                ('items', models.CharField(max_length=1000)),
                ('total', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('category', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='photos/product')),
                ('claimed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
